from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('session-check/', views.session_check, name='session_check'),
    path('access-denied/', views.access_denied, name='access_denied'),
    path('logout/', views.logout_view, name='logout'),
    path('settings/', views.account_settings, name='account_settings'),
    path('profile-settings/', views.profile_settings, name='profile_settings'),
    path('business-info/', views.business_info, name='business_info'),
    path('email-settings/test/', views.test_email_settings, name='test_email_settings'),
    path('system-settings/', views.system_settings, name='system_settings'),
    path('screen-timeout/', views.screen_timeout, name='screen_timeout'),
    path('manage-devices/', views.manage_devices, name='manage_devices'),
    path('toggle-device-block/<int:pk>/', views.toggle_device_block, name='toggle_device_block'),
    path('terminate-session/<int:pk>/', views.terminate_session, name='terminate_session'),
    path('unterminate-session/<int:pk>/', views.unterminate_session, name='unterminate_session'),
    path('delete-device/<int:pk>/', views.delete_device, name='delete_device'),
    path('api/send-user-message/', views.send_user_message, name='send_user_message'),
    path('api/poll-messages/', views.poll_messages, name='poll_messages'),
    path('api/get-conversation/', views.get_conversation, name='get_conversation'),
    path('api/get-all-users/', views.get_all_users, name='get_all_users'),
    path('api/get-my-conversations/', views.get_my_conversations, name='get_my_conversations'),

    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('cashier-dashboard/', views.cashier_dashboard, name='cashier_dashboard'),
    path('api/admin-dashboard-data/', views.admin_dashboard_chart_data, name='admin_dashboard_chart_data'),
    path('api/admin-chart-released/', views.admin_chart_released_data, name='admin_chart_released_data'),
    path('api/admin-suppliers-chart/', views.admin_suppliers_chart_data, name='admin_suppliers_chart_data'),
    path('api/check-validator/lookup/', views.check_validator_lookup, name='check_validator_lookup'),
    path('api/check-validator/release/', views.check_validator_release, name='check_validator_release'),
    path('api/cashier-dashboard-data/', views.cashier_dashboard_chart_data, name='cashier_dashboard_chart_data'),
    path('api/cashier-suppliers-chart/', views.cashier_suppliers_chart_data, name='cashier_suppliers_chart_data'),
    path('api/next-supplier-sequences/', views.next_supplier_sequences, name='next_supplier_sequences'),
    path('transactions/', views.admin_transactions, name='admin_transactions'),
    path('cashier-transactions/', views.cashier_transactions, name='cashier_transactions'),

    path('user-management/', views.user_management, name='user_management'),
    path('create-cashier/', views.user_management, name='create_cashier'),

    path('fund-clusters/', views.fund_clusters, name='fund_clusters'),
    path('account-titles/', views.account_titles_management, name='account_titles_management'),
    path('account-titles/<int:pk>/', views.account_title_group_detail, name='account_title_group_detail'),
    path('account-titles/<int:pk>/api/', views.account_title_group_api, name='account_title_group_api'),
    path('account-titles/import/preview/', views.account_titles_import_preview, name='account_titles_import_preview'),
    path('taxes/', views.taxes_management, name='taxes_management'),
    path('suppliers/', views.suppliers, name='suppliers'),
    path('cashier/suppliers/', views.suppliers, name='cashier_suppliers'),
    path('suppliers/<int:pk>/update-remark/', views.update_supplier_remark, name='update_supplier_remark'),
    path('radai/', views.radai, name='radai'),
    path('cashier/radai/', views.radai, name='cashier_radai'),
    path('radai/<int:pk>/detail/', views.radai_detail, name='radai_detail'),
    path('radai/<int:pk>/update-remark/', views.update_radai_remark, name='update_radai_remark'),
    path('radai/settings/', views.update_radai_settings, name='update_radai_settings'),
    path('export/radai/', views.export_radai, name='export_radai'),
    path('registry/', views.registry, name='registry'),

    path('cheques/', views.cheque_list, name='cheque_list'),
    path('cheques/new/', views.cheque_create, name='cheque_create'),
    path('cheques/lookup/', views.cheque_lookup, name='cheque_lookup'),
    path('cheques/<int:pk>/edit/', views.cheque_edit, name='cheque_edit'),
    path('cheques/<int:pk>/print/', views.cheque_print, name='cheque_print'),
    path('cheques/<int:pk>/pdf/', views.cheque_pdf, name='cheque_pdf'),
    path('cheques/<int:pk>/void/', views.cheque_void, name='cheque_void'),
    path('cheques/<int:pk>/delete/', views.cheque_delete, name='cheque_delete'),
    path('cheques/<int:pk>/advance/', views.cheque_advance_status, name='cheque_advance_status'),

    path('reports/', views.reports, name='reports'),
    path('reports/<int:pk>/', views.report_detail, name='report_detail'),
    path('reports/<int:pk>/delete/', views.report_delete, name='report_delete'),
    path('reports/<int:pk>/print/', views.report_print, name='report_print'),
    path('reports/<int:pk>/print/modal/', views.report_print_modal, name='report_print_modal'),
    path('reports/export/preview/', views.report_export_preview, name='report_export_preview'),
    path('reports/export/pdf/', views.export_report_pdf, name='export_report_pdf'),
    path('reports/fund-cluster-info/', views.fund_cluster_info, name='fund_cluster_info'),

    path('import/', views.import_data, name='import_data'),
    path('import/template/', views.download_import_template, name='download_import_template'),
    path('export/cheques/', views.export_cheques, name='export_cheques'),
    path('export/suppliers/', views.export_suppliers, name='export_suppliers'),

    path('audit-log/', views.audit_log, name='audit_log'),
    path('remark-mgm/', views.remark_management, name='remark_management'),

    path('rfid-scan/', views.rfid_lookup, name='rfid_lookup'),
    path('rfid-auth/', views.rfid_auth, name='rfid_auth'),
    path('role-permissions/', views.role_permissions, name='role_permissions'),
    path('role-permissions/save/', views.save_role_permissions, name='save_role_permissions'),
    path('backup-restore/', views.backup_restore, name='backup_restore'),
    path('start-fingerprint-enroll/', views.start_fingerprint_enroll, name='start_fingerprint_enroll'),
    path('start-face-enroll/', views.start_face_enroll, name='start_face_enroll'),
    path('face-enroll/', views.face_enroll, name='face_enroll'),
    path('voice-enroll/', views.voice_enroll, name='voice_enroll'),
    path('verify-password/', views.verify_password, name='verify_password'),
    path('lockscreen/', views.lockscreen_view, name='lockscreen'),
    path('lock/', views.trigger_lock, name='trigger_lock'),
    path('about/', views.about_view, name='about_system'),
    path('about-cashier/', views.about_cashier_view, name='about_cashier'),
    path('mfa/setup/', views.mfa_setup, name='mfa_setup'),
    path('mfa/totp-qr/', views.mfa_totp_qr, name='mfa_totp_qr'),
    path('mfa/resend-email-otp/', views.mfa_resend_email_otp, name='mfa_resend_email_otp'),
    path('mfa/regenerate-recovery-codes/', views.mfa_regenerate_recovery_codes, name='mfa_regenerate_recovery_codes'),
    path('mfa/send-disable-email-otp/', views.mfa_send_disable_email_otp, name='mfa_send_disable_email_otp'),
    path('mfa/send-disable-totp-otp/', views.mfa_send_disable_totp_otp, name='mfa_send_disable_totp_otp'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('check-user-exists/', views.check_user_exists, name='check_user_exists'),
    path('email-settings/', views.email_settings, name='email_settings'),
    path('chatbot-setup/', views.chatbot_setup, name='chatbot_setup'),
    path('chatbot/config/', views.chatbot_config_api, name='chatbot_config_api'),
    path('chatbot/message/', views.chatbot_message_api, name='chatbot_message_api'),
    path('chatbot/clear-history/', views.chatbot_clear_history, name='chatbot_clear_history'),
    path('chatbot/history/', views.chatbot_history_api, name='chatbot_history_api'),
    path('admin-user-manual/', views.admin_user_manual, name='admin_user_manual'),
    path('cashier-user-manual/', views.cashier_user_manual, name='cashier_user_manual'),
]
