# Generated by Django 6.0.4 on 2026-04-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
