# Generated by Django 6.0.4 on 2026-04-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_profile_device_token_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='face_image',
        ),
    ]
