# Generated by Django 6.0.4 on 2026-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_remove_profile_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='face_embedding',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/face/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_template',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/fingerprint/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended'), ('pending', 'Pending Activation')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('guest', 'Guest Viewer')], default='cashier', max_length=20),
        ),
    ]
