# Generated by Django 6.0.4 on 2026-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_fundcluster_supplier_report_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcluster',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
