# Generated by Django 6.0.4 on 2026-05-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_fix_fundcluster_balance_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
