# Generated by Django 6.0.4 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_supplier_raw_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcluster',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundcluster',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]