"""Add stale_after_days and stale_at to Cheque

Generated by hand to add timer fields for stale cheques.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_supplier_collection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='stale_after_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='stale_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
