# Generated by Django 6.0.4 on 2026-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0015_add_stale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='dv_payroll_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='DV/Payroll No.'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='nature_of_payment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nature of Payment'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='ors_burs_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='ORS/BURS No.'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='professional_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Professional Tax'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='responsibility_center',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Responsibility Center Code'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='tax_3_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Tax 3%/1%'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='tax_5_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Tax 5%/3%'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='uacs_object_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='UACS Object Code'),
        ),
    ]
