# Generated by Django 6.0.5 on 2026-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_add_cheque_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_disbursing_officer',
            field=models.BooleanField(default=False),
        ),
    ]
