# Generated by Django 6.0.4 on 2026-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0017_profile_is_disbursing_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
