# Generated by Django 6.0.4 on 2026-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0020_profile_email_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
