# Generated by Django 6.0.4 on 2026-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0021_profile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lockscreen_wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='lockscreen_wallpapers/'),
        ),
    ]
