# Generated by Django 6.0.4 on 2026-06-10 02:48

import admin_panel.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0022_profile_lockscreen_wallpaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadaiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ors_burs_no', models.CharField(blank=True, default='', max_length=60, verbose_name='ORS/BURS No.')),
                ('responsibility_center', models.CharField(blank=True, default='', max_length=60, verbose_name='Responsibility Center Code')),
            ],
            options={
                'verbose_name': 'RADAI Setting',
                'verbose_name_plural': 'RADAI Settings',
            },
        ),
        migrations.CreateModel(
            name='Radai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_or', models.CharField(blank=True, default='', max_length=60)),
                ('mr', models.CharField(blank=True, default='', max_length=120)),
                ('code_or', models.CharField(blank=True, default='', max_length=60)),
                ('code_or2', models.CharField(blank=True, default='', max_length=60)),
                ('series_month', models.CharField(blank=True, default='', max_length=40)),
                ('date', models.DateField(blank=True, null=True)),
                ('or_number', models.CharField(blank=True, default='', max_length=60)),
                ('series_day', models.CharField(blank=True, default='', max_length=40)),
                ('account_number', admin_panel.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(max_length=200)),
                ('code_line', models.CharField(blank=True, default='', max_length=80)),
                ('line', models.CharField(blank=True, default='', max_length=80)),
                ('code_noc', models.CharField(blank=True, default='', max_length=80)),
                ('nature_of_collections', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('tin', models.CharField(blank=True, default='', max_length=30, verbose_name='TIN')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('raw_import', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radai_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
