# Generated by Django 6.0.4 on 2026-06-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0023_radai_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='radai',
            name='fund_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.fundcluster', verbose_name='Fund Cluster'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('cheque_summary', 'Cheque Summary'), ('fund_summary', 'Fund Cluster Summary'), ('supplier_summary', 'Supplier Summary'), ('radai_summary', 'RADAI Summary'), ('audit_summary', 'Audit Log Summary')], max_length=40),
        ),
    ]
