# Generated by Django 6.0.4 on 2026-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0024_radai_fund_cluster_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='radai',
            name='ors_burs_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='ORS/BURS No.'),
        ),
        migrations.AddField(
            model_name='radai',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ORS/BURS No. & Responsibility Center'),
        ),
        migrations.AddField(
            model_name='radai',
            name='responsibility_center',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Responsibility Center Code'),
        ),
    ]
