# Generated by Django 6.0.6 on 2026-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0027_profile_blocked_login_ip_profile_blocked_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='current_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
