# Generated by Django 6.0.6 on 2026-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_userdevice_current_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_lock_seconds',
            field=models.IntegerField(blank=True, help_text='Individual idle seconds before lock screen warning', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_logout_seconds',
            field=models.IntegerField(blank=True, help_text='Individual idle seconds before logout', null=True),
        ),
    ]
