# Generated by Django 6.0.6 on 2026-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_profile_auto_lock_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
