# Generated by Django 6.0.6 on 2026-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0030_userdevice_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.CharField(blank=True, choices=[('', 'Custom Range'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('cheque_summary', 'Cheque Summary'), ('radai_summary', 'RADAI Summary'), ('weekly_cheque', 'Weekly Cheque Report'), ('monthly_cheque', 'Monthly Cheque Report'), ('annual_cheque', 'Annual Cheque Report'), ('weekly_radai', 'Weekly RADAI Report'), ('monthly_radai', 'Monthly RADAI Report'), ('annual_radai', 'Annual RADAI Report')], max_length=40),
        ),
    ]
