# Generated by Django 6.0.6 on 2026-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0031_report_period_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Activation'), ('resting', 'Resting'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='pending', max_length=30),
        ),
    ]
