# Generated by Django 6.0.6 on 2026-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0032_update_profile_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_recovery_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of unused recovery codes for MFA fallback'),
        ),
    ]
