# Generated by Django 6.0.6 on 2026-08-21 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0033_add_mfa_recovery_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['status'], name='cashier_che_status_e1786a_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['date'], name='cashier_che_date_e9d7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['cheque_number'], name='cashier_che_cheque__f7f602_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['payee'], name='cashier_che_payee_i_b7a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['fund_cluster'], name='cashier_che_fund_cl_47c688_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['created_by'], name='cashier_che_created_eb175c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['account_name'], name='cashier_sup_account_9e92d9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='cashier_sup_status_93a153_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['date'], name='cashier_sup_date_2a54a3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['created_by'], name='cashier_sup_created_e7b570_idx'),
        ),
    ]
