# Generated by Django 6.0.6 on 2026-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0034_cheque_cashier_che_status_e1786a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
