# Generated by Django 6.0.6 on 2026-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0035_add_cheque_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('budget_accounting', 'Budget Accounting'), ('guest', 'Guest Viewer')], default='cashier', max_length=20),
        ),
    ]
