# Generated by Django 6.0.6 on 2026-09-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0036_add_budget_accounting_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
