# Generated by Django 6.0.6 on 2026-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0038_cheque_archived_at_cheque_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specific_role',
            field=models.CharField(blank=True, default='', help_text='Specific role label for Guest Viewer users', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('cheque_summary', 'Cheque Summary'), ('radai_summary', 'RADAI Summary')], max_length=40),
        ),
    ]
