# Generated by Django 6.0.4 on 2026-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='registry', max_length=120)),
                ('system_logo', models.ImageField(blank=True, null=True, upload_to='system_assets/')),
            ],
        ),
    ]
