# Generated by Django 6.0.4 on 2026-04-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_systemsetting_enable_device_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='enable_device_link',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='enable_email_verification',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='enable_face_recognition',
        ),
    ]
