# Generated by Django 6.0.4 on 2026-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='last_cheque_number',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
