# Generated by Django 6.0.4 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_systemsetting_last_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='entity_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='last_report_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]