# Generated by Django 6.0.4 on 2026-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_managementoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementoption',
            name='category',
            field=models.CharField(choices=[('account_title', 'Account Title'), ('remark', 'Remark'), ('tax', 'Tax')], db_index=True, max_length=40),
        ),
    ]
