# Generated by Django 6.0.4 on 2026-06-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_add_cheque_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementoption',
            name='uacs',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
