# Generated by Django 6.0.4 on 2026-06-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_add_account_title_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttitlegroup',
            name='uacs',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
