# Generated by Django 6.0.5 on 2026-06-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_add_uacs_to_account_title_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='lockscreen_wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='system_assets/'),
        ),
    ]
