# Generated by Django 6.0.5 on 2026-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_systemsetting_lockscreen_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auto_lock_seconds',
            field=models.IntegerField(default=30, help_text='Idle seconds before auto-lock warning (min 10, max 3600)'),
        ),
    ]
