# Generated by Django 6.0.4 on 2026-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_add_auto_lock_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auto_logout_seconds',
            field=models.IntegerField(default=3600, help_text='Idle seconds before automatic logout (min 60, max 86400)'),
        ),
    ]
