# Generated by Django 6.0.4 on 2026-06-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_add_auto_logout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
