# Generated by Django 6.0.6 on 2026-07-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_systemsetting_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI Assistant', help_text='Name of the chatbot assistant', max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini')], default='openai', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key for the AI provider', max_length=500)),
                ('model_name', models.CharField(blank=True, default='gpt-4o-mini', help_text='Model name (e.g. gpt-4o-mini, claude-3-haiku, gemini-2.0-flash)', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='You are a helpful assistant for a financial registry system. Be concise and professional.', help_text="System prompt that defines the assistant's behavior")),
                ('welcome_message', models.CharField(blank=True, default="Hi! I'm your AI assistant. How can I help you today?", help_text='First message shown to users', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='Enable the chatbot for users')),
                ('max_history', models.IntegerField(default=20, help_text='Maximum number of messages to keep in context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users who can access the chatbot. Leave empty for admin only.', related_name='chatbot_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
