# Generated by Django 6.0.6 on 2026-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_chatbotconfig_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='Custom base URL (for Ollama, Custom, or self-hosted endpoints)', max_length=500),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('xai', 'xAI (Grok)'), ('openrouter', 'OpenRouter'), ('together', 'Together AI'), ('cohere', 'Cohere'), ('huggingface', 'Hugging Face'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom (OpenAI-Compatible)')], default='openai', max_length=20),
        ),
    ]
