# Generated by Django 6.0.6 on 2026-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_chatbotconfig_allowed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='system_logo_hover',
            field=models.ImageField(blank=True, help_text='Image shown when hovering over the login logo to prevent downloading', null=True, upload_to='system_assets/'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text="System prompt that defines the assistant's behavior"),
        ),
    ]
