# Generated by Django 6.0.6 on 2026-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_systemsetting_system_logo_hover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_bg_color', models.CharField(default='#eef3f7', help_text='Main background color', max_length=20)),
                ('site_bg_image', models.ImageField(blank=True, help_text='Background image (overrides color)', null=True, upload_to='system_assets/')),
                ('card_color', models.CharField(default='#ffffff', help_text='Card/panel background color', max_length=20)),
                ('accent_color', models.CharField(default='#2f80ed', help_text='Primary accent color (buttons, links)', max_length=20)),
                ('accent_hover_color', models.CharField(default='#1f67c2', help_text='Accent hover color', max_length=20)),
                ('header_color', models.CharField(default='#0e2d0a', help_text='Top header/navbar color', max_length=20)),
                ('sidenav_color', models.CharField(default='#0e2d0a', help_text='Side navigation color', max_length=20)),
                ('text_color', models.CharField(default='#1f2a37', help_text='Primary text color', max_length=20)),
                ('muted_color', models.CharField(default='#667085', help_text='Muted/secondary text color', max_length=20)),
                ('border_color', models.CharField(default='#d9e1ea', help_text='Border/divider color', max_length=20)),
                ('success_color', models.CharField(default='#16a34a', help_text='Success state color', max_length=20)),
                ('warning_color', models.CharField(default='#d97706', help_text='Warning state color', max_length=20)),
                ('danger_color', models.CharField(default='#dc2626', help_text='Danger/error state color', max_length=20)),
                ('heading_font', models.CharField(default='Inter', help_text='Google Font name for headings', max_length=100)),
                ('body_font', models.CharField(default='Inter', help_text='Google Font name for body text', max_length=100)),
                ('header_accent_line', models.CharField(default='#facc15', help_text='Header accent line color', max_length=20)),
            ],
            options={
                'verbose_name': 'Web Theme Setting',
                'verbose_name_plural': 'Web Theme Settings',
            },
        ),
    ]
