# Generated by Django 6.0.6 on 2026-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_systemsetting_system_logo_hover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='default_from_email',
            field=models.CharField(blank=True, default='', help_text='Default sender email address', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_backend',
            field=models.CharField(blank=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Django email backend class', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server host', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='SMTP password or app password', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_host_user',
            field=models.CharField(blank=True, default='', help_text='SMTP username / email address', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
    ]
