# Generated by Django 6.0.6 on 2026-07-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_webthemesetting'),
        ('admin_panel', '0020_add_email_settings'),
    ]

    operations = [
    ]
