# Generated by Django 6.0.6 on 2026-08-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_merge_0019_webthemesetting_0020_add_email_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebThemeSetting',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='login_background',
            field=models.ImageField(blank=True, help_text='Background image shown on the login page', null=True, upload_to='system_assets/'),
        ),
    ]
