# Generated by Django 6.0.6 on 2026-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_delete_webthemesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='last_dv_payroll_no',
            field=models.CharField(blank=True, default='', help_text='Last DV/Payroll number sequence (YYYY-MM-NNNN)', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='last_ors_burs_no',
            field=models.CharField(blank=True, default='', help_text='Last ORS/BURS number sequence', max_length=30),
        ),
    ]
