# Generated by Django 6.0.6 on 2026-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_add_dv_ors_sequence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='retention_auto_delete',
            field=models.BooleanField(default=False, help_text='Automatically delete old backups based on policy'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retention_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic backup retention policy'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retention_max_age_days',
            field=models.IntegerField(default=90, help_text='Delete backups older than this many days'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retention_max_count',
            field=models.IntegerField(default=10, help_text='Maximum number of backups to keep (0 = unlimited)'),
        ),
    ]
