# Generated by Django 6.0.6 on 2026-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic 5-day backup'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='auto_backup_interval_days',
            field=models.IntegerField(default=5, help_text='Frequency of automatic backups in days'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='auto_backup_to_downloads',
            field=models.BooleanField(default=True, help_text="Copy backup to user's local Downloads folder"),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='last_auto_backup',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last automatic backup', null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='last_auto_backup_file',
            field=models.CharField(blank=True, default='', help_text='Filename of the last automatic backup', max_length=255),
        ),
    ]
